version: '3'
services:
    db:
        build:
            context: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=product
            - MYSQL_USER=product_u
            - MYSQL_PASSWORD=012n1bsdiu
        container_name: golang_db
        ports:
            - "3306:3306"
        tty: true
    # app:
    #     build:
    #         context: ./go
    #     volumes:
    #         - "./Go:/go"
    #     container_name: golang_app
    #     ports:
    #         - "8080:8080"
    #     tty: true
    #     stdin_open: true
    #     depends_on:
    #         - db